### ISSUE TITLE
Game mechanics

### ISSUE THREAD

**Issue by Lionex** [Lionex/regroup#1]
The game is based on being able to drag-and-drop objects into containers to sort them, and thus there are 3 key game mechanics:

- [x] Drag-and-drop elements #2 
- [x] Place them into a container #3
- [x] Randomly generate objects with sort-able characteristics #4

This is considered the minimum viable product for this game, and thus they are the most important elements to finish during the hackathon.
